ParameterDefinitions = { 

{g1,        { Description -> "Hypercharge-Coupling"}},
{gX,       {LaTeX -> "g_X",
             LesHouches -> {GAUGE,4},
             OutputName -> gX}},

{g1X,       {LaTeX -> "\\tilde{g}",
             LesHouches -> {GAUGE,10},
             OutputName -> g1X}},
{gX1,       {LaTeX -> "\\bar{g}",
             LesHouches -> {GAUGE,11},
             OutputName -> gX1}},
{g2,        { Description -> "Left-Coupling"}},
{g3,        { Description -> "Strong-Coupling"}},    
{AlphaS,    {Description -> "Alpha Strong"}},	
{e,         { Description -> "electric charge"}}, 

{Gf,        { Description -> "Fermi's constant"}},
{aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},

{Yu,        { Description -> "Up-Yukawa-Coupling",
			 DependenceNum ->  Sqrt[2]/v* {{Mass[Fu,1],0,0},
             									{0, Mass[Fu,2],0},
             									{0, 0, Mass[Fu,3]}}}}, 
             									
{Yd,        { Description -> "Down-Yukawa-Coupling",
			  DependenceNum ->  Sqrt[2]/v* {{Mass[Fd,1],0,0},
             									{0, Mass[Fd,2],0},
             									{0, 0, Mass[Fd,3]}}}},
             									
{Ye,        { Description -> "Lepton-Yukawa-Coupling",
			  DependenceNum ->  Sqrt[2]/v* {{Mass[Fe,1],0,0},
             									{0, Mass[Fe,2],0},
             									{0, 0, Mass[Fe,3]}}}}, 
                                                                            
{mS2,       {LaTeX -> "m_S^2",
             LesHouches -> {BSM,1},
             OutputName -> MS2}},
{L1,       {LaTeX -> "\\lambda_1",
             LesHouches -> {BSM,2},
             OutputName -> LAM1}},
{L2,       {LaTeX -> "\\lambda_2",
             LesHouches -> {BSM,3},
             OutputName -> LAM2}},
{mSG2,       {LaTeX -> "m_{\\sigma}^2",
             LesHouches -> {BSM,4},
             OutputName -> MSG2}},
{L3,       {LaTeX -> "\\lambda_3",
             LesHouches -> {BSM,5},
             OutputName -> LAM3}},
{L4,       {LaTeX -> "\\lambda_4",
             LesHouches -> {BSM,6},
             OutputName -> LAM4}},
{L5,       {LaTeX -> "\\lambda_5",
             LesHouches -> {BSM,7},
             OutputName -> LAM5}},
{vS,      {  LaTeX -> "vS",
             Dependence ->  None,
             OutputName -> "vS",
             Real -> True,
             LesHouches -> {BS,4} }},
{mNR, {OutputName -> MNR,
      LaTeX -> "m_{\\nu_R}",
      LesHouches -> MNR}},
{mSG22,       {LaTeX -> "m_{\\sigma_2}^2",
             LesHouches -> {BSM,8},
             OutputName -> MSG22}},
{L4,       {LaTeX -> "\\lambda_4",
             LesHouches -> {BSM,9},
             OutputName -> LAM4}},
{L5,       {LaTeX -> "\\lambda_5",
             LesHouches -> {BSM,10},
             OutputName -> LAM5}},
{L6,       {LaTeX -> "\\lambda_6",
             LesHouches -> {BSM,11},
             OutputName -> LAM6}},
{L7,       {LaTeX -> "\\lambda_7",
             LesHouches -> {BSM,12},
             OutputName -> LAM7}},
{L8,       {LaTeX -> "\\lambda_8",
             LesHouches -> {BSM,13},
             OutputName -> LAM8}},
{L9,       {LaTeX -> "\\lambda_9",
             LesHouches -> {BSM,14},
             OutputName -> LAM9}},
{mET2,       {LaTeX -> "m_{\\eta}^2",
             LesHouches -> {BSM,15},
             OutputName -> MET2}},
{L10,       {LaTeX -> "\\lambda_{10}",
             LesHouches -> {BSM,16},
             OutputName -> LAM10}},
{L11,       {LaTeX -> "\\lambda_{11}",
             LesHouches -> {BSM,17},
             OutputName -> LAM11}},
{L12,       {LaTeX -> "\\lambda_{12}",
             LesHouches -> {BSM,18},
             OutputName -> LAM12}},
{L13,       {LaTeX -> "\\lambda_{13}",
             LesHouches -> {BSM,19},
             OutputName -> LAM13}},
{L14,       {LaTeX -> "\\lambda_{14}",
             LesHouches -> {BSM,20},
             OutputName -> LAM14}},
{L15,       {LaTeX -> "\\lambda_{15}",
             LesHouches -> {BSM,21},
             OutputName -> LAM15}},
{mET22,       {LaTeX -> "m_{\\eta_2}^2",
             LesHouches -> {BSM,22},
             OutputName -> MET22}},
{L16,       {LaTeX -> "\\lambda_{16}",
             LesHouches -> {BSM,23},
             OutputName -> LAM16}},
{L17,       {LaTeX -> "\\lambda_{17}",
             LesHouches -> {BSM,24},
             OutputName -> LAM17}},
{L18,       {LaTeX -> "\\lambda_{18}",
             LesHouches -> {BSM,25},
             OutputName -> LAM18}},
{L19,       {LaTeX -> "\\lambda_{19}",
             LesHouches -> {BSM,26},
             OutputName -> LAM19}},
{L20,       {LaTeX -> "\\lambda_{20}",
             LesHouches -> {BSM,27},
             OutputName -> LAM20}},
{L21,       {LaTeX -> "\\lambda_{21}",
             LesHouches -> {BSM,28},
             OutputName -> LAM21}},
{L22,       {LaTeX -> "\\lambda_{22}",
             LesHouches -> {BSM,29},
             OutputName -> LAM22}},
{mCL,       {LaTeX -> "m_{\\chi_L}",
             LesHouches -> {BSM,30},
             OutputName -> MCL}},
{mCR,       {LaTeX -> "m_{\\chi_R}",
             LesHouches -> {BSM,31},
             OutputName -> MCR}},
{mCL2,       {LaTeX -> "m_{\\chi_{L2}}",
             LesHouches -> {BSM,32},
             OutputName -> MCL2}},
{mCR2,       {LaTeX -> "m_{\\chi_{R2}}",
             LesHouches -> {BSM,33},
             OutputName -> MCR2}},
{Y,          {LaTeX -> "Y",
             LesHouches -> {BSM,34},
             OutputName -> Y}},
{Y1,       {LaTeX -> "Y_1",
             LesHouches -> {BSM,35},
             OutputName -> Y1}},
{Y2,       {LaTeX -> "Y_2",
            LesHouches -> {BSM,36},
             OutputName -> Y2}},
{Y3,       {LaTeX -> "Y_3",
             LesHouches -> Y3,
             OutputName -> Y3}},
{Y4,       {LaTeX -> "Y_4",
             LesHouches -> {BSM,37},
             OutputName -> Y4}},
{Y5,       {LaTeX -> "Y_5",
             LesHouches -> Y5,
             OutputName -> Y5}},
{YS,       {LaTeX -> "Y_S",
             LesHouches -> {BSM,38},
             OutputName -> YS}},
{YS1,       {LaTeX -> "Y_{S1}",
             LesHouches -> {BSM,39},
             OutputName -> YS1}},
{LS4,       {LaTeX -> "L_{S4}",
             LesHouches -> {BSM,40},
             OutputName -> LS4}},
             {mu2,         { Description -> "SM Mu Parameter",
                OutputName->m2SM}},                                        
{\[Lambda],  { Description -> "SM Higgs Selfcouplings",
               DependenceNum -> Mass[hh]^2/(v^2)}},
{v,          { Description -> "EW-VEV",
               DependenceNum -> Sqrt[4*Mass[VWp]^2/(g2^2)],
               DependenceSPheno -> None,
               OutputName -> vvSM}},
{mH2,        { Description -> "SM Higgs Mass Parameter"}},
{ThetaWp,    { Description -> "Theta'", DependenceNum -> None  }},
{ThetaW,     { Description -> "Weinberg-Angle",
              DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]  }},
{ZW, {Description -> "W Mixing Matrix",
       Dependence ->   1/Sqrt[2] {{1, 1},
                  {\[ImaginaryI],-\[ImaginaryI]}} }},
{ZZ, {Description ->   "Photon-Z-Z' Mixing Matrix"}},

{Vu,        {Description ->"Left-Up-Mixing-Matrix"}},
{Vd,        {Description ->"Left-Down-Mixing-Matrix"}},
{Uu,        {Description ->"Right-Up-Mixing-Matrix"}},
{Ud,        {Description ->"Right-Down-Mixing-Matrix"}}, 
{Ve,        {Description ->"Left-Lepton-Mixing-Matrix"}},
{Ue,        {Description ->"Right-Lepton-Mixing-Matrix"}},
{ZH,        { Description->"Scalar-Mixing-Matrix",
               Dependence -> None,
               DependenceOptional -> None,
               DependenceNum -> None   }},
{ZA,        { Description->"Pseudo-Scalar-Mixing-Matrix",
                Dependence -> None,
               DependenceOptional -> None,
               DependenceNum -> None   }},
{ZM,	    {Description -> "Neutrino-Mixing-Matrix"}}
 }; 
 

