ParameterDefinitions = { 

{g1,        { Description -> "Hypercharge-Coupling"}},
{gX,       {LaTeX -> "g_X",
             LesHouches -> {GAUGE,4},
             OutputName -> gX}},

{g1X,       {LaTeX -> "\\tilde{g}",
             LesHouches -> {GAUGE,10},
             OutputName -> g1X}},
{gX1,       {LaTeX -> "\\bar{g}",
             LesHouches -> {GAUGE,11},
             OutputName -> gX1}},
{g2,        { Description -> "Left-Coupling"}},
{g3,        { Description -> "Strong-Coupling"}},    
{AlphaS,    {Description -> "Alpha Strong"}},	
{e,         { Description -> "electric charge"}}, 

{Gf,        { Description -> "Fermi's constant"}},
{aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},

{Yu,        { Description -> "Up-Yukawa-Coupling",
			 DependenceNum ->  Sqrt[2]/v* {{Mass[Fu,1],0,0},
             									{0, Mass[Fu,2],0},
             									{0, 0, Mass[Fu,3]}}}}, 
             									
{Yd,        { Description -> "Down-Yukawa-Coupling",
			  DependenceNum ->  Sqrt[2]/v* {{Mass[Fd,1],0,0},
             									{0, Mass[Fd,2],0},
             									{0, 0, Mass[Fd,3]}}}},
             									
{Ye,        { Description -> "Lepton-Yukawa-Coupling",
			  DependenceNum ->  Sqrt[2]/v* {{Mass[Fe,1],0,0},
             									{0, Mass[Fe,2],0},
             									{0, 0, Mass[Fe,3]}}}}, 
                                                                            
{mS2,       {LaTeX -> "m_S^2",
             LesHouches -> {BSM,1},
             OutputName -> MS2}},
{L1,       {LaTeX -> "\\lambda_1",
             LesHouches -> {BSM,2},
             OutputName -> LAM1}},
{L2,       {LaTeX -> "\\lambda_2",
             LesHouches -> {BSM,3},
             OutputName -> LAM2}},
{vS,      {  LaTeX -> "vS",
             Dependence ->  None,
             OutputName -> "vS",
             Real -> True,
             LesHouches -> {BS,4} }},
{T1, {OutputName -> T1,
      LaTeX -> "T1",
      LesHouches -> T1}},
{mNR, {OutputName -> MNR,
      LaTeX -> "m_{\\nu_R}",
      LesHouches -> MNR}},
{T2, {OutputName -> T2,
      LaTeX -> "T2",
      LesHouches -> T2}},
             {mu2,         { Description -> "SM Mu Parameter",
                OutputName->m2SM}},                                        
{\[Lambda],  { Description -> "SM Higgs Selfcouplings",
               DependenceNum -> Mass[hh]^2/(v^2)}},
{v,          { Description -> "EW-VEV",
               DependenceNum -> Sqrt[4*Mass[VWp]^2/(g2^2)],
               DependenceSPheno -> None,
               OutputName -> vvSM}},
{mH2,        { Description -> "SM Higgs Mass Parameter"}},
{ThetaWp,    { Description -> "Theta'", DependenceNum -> None  }},
{ThetaW,     { Description -> "Weinberg-Angle",
              DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]  }},
{ZW, {Description -> "W Mixing Matrix",
       Dependence ->   1/Sqrt[2] {{1, 1},
                  {\[ImaginaryI],-\[ImaginaryI]}} }},
{ZZ, {Description ->   "Photon-Z-Z' Mixing Matrix"}},

{Vu,        {Description ->"Left-Up-Mixing-Matrix"}},
{Vd,        {Description ->"Left-Down-Mixing-Matrix"}},
{Uu,        {Description ->"Right-Up-Mixing-Matrix"}},
{Ud,        {Description ->"Right-Down-Mixing-Matrix"}}, 
{Ve,        {Description ->"Left-Lepton-Mixing-Matrix"}},
{Ue,        {Description ->"Right-Lepton-Mixing-Matrix"}},
{ZH,        { Description->"Scalar-Mixing-Matrix",
               Dependence -> None,
               DependenceOptional -> None,
               DependenceNum -> None   }},
{ZA,        { Description->"Pseudo-Scalar-Mixing-Matrix",
                Dependence -> None,
               DependenceOptional -> None,
               DependenceNum -> None   }},
{ZM,	    {Description -> "Neutrino-Mixing-Matrix"}}
 }; 
 

